### ISSUE TITLE
Grails 4 project gets error when built against plugin v.5.0 Failed to initialize class [com.demo.DemoController]

### ISSUE THREAD

**Issue by joelbard** [grails-plugins/grails-cache#139]
Default build.gradle from create-app has cache plugin with no version number.  When v.5.0 of the plugin was released a clean build pulled in the new version but then failed to start when war was deployed to tomcat 9.  Specifying v.4.0.3 in build.gradle fixes the problem.   This is a large grails 4 application using 4.0.11 to build.

Error in catalina.out was:
```
2022-03-16 04:06:48.914 ERROR -- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostProcessor' defined in gdbxt.Application: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is grails.plugins.exceptions.PluginException: Failed to initialize class [com.demo.DemoController] from plugin [cache] : com.demo.DemoController
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:456)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1318)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:118)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:706)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at grails.boot.GrailsApp.run(GrailsApp.groovy:99)
```
etc.

**Comment by amasr** [comment]
@joelbard We had the same problem and fixed as a temporary workaround by rollingback to version 5.0.0.RC1.
It was tricky to find because cached gradle deps weren't failing, it was from the CI that we step into it, and then with --refresh-dependencies flag to reproduce it.
could it be something missing in the bulid.gradle or grails-plugin.xml (excludePagackes) ?
https://github.com/grails/grails-core/issues/9416


Looking at .../src/main/groovy/grails/plugin/CacheGrailsPlugin.groovy looks like it is missing 
`def pluginExcludes = [ "**/com/demo/*", grails-app/views/**, **/*.gsp ]`

Not sure if thats is intended, but the generated grails-plugin.xml within the manifest doesn't excludes the demo elements.

@davidkron Not my intention to bother, but I'm sure you have more knowledge than me on this issue.

**Comment by puneetbehl** [comment]
I have released version 5.0.1 to Maven Central which should be same as the previous 5.0.0 release. Please let me know if this works.

**Comment by davidkron** [comment]
@amasr It seems my PR where I removed `pluginExcludes` did produce this error as this property seems to be still used when generating the `grails-plugin.xml` file.
I think it should be sufficient to revert `CacheGrailsPlugin.groovy` back to the previous state: https://github.com/grails/grails-cache/blob/be6cefecaf954df6430ce9aefc6949d76208fde6/src/main/groovy/grails/plugin/cache/CacheGrailsPlugin.groovy

Sorry for the trouble!

**Comment by joelbard** [comment]
I'm able to run the application using 5.0.1.  Thanks for the quick fix!
