### ISSUE TITLE
Project build fails using annotations @Cacheable, @CacheEvict

### ISSUE THREAD

**Issue by virtualcook** [grails-plugins/grails-cache#41]
Plugin does not work on Grails 3.2.8
1) Into build.gradle added
dependencies {
    compile 'org.grails.plugins:cache:4.0.0.M1'
}
2) Into gradle.properties added
gormVersion=6.1.0.RELEASE
--------
gradlew build 
fails with
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.buildDelegatingMethodCall(Lorg/codehaus/groovy/control/SourceUnit;Lorg/codehaus/groovy/ast/Annotat
ionNode;Lorg/codehaus/groovy/ast/ClassNode;Lorg/codehaus/groovy/ast/MethodNode;Lorg/codehaus/groovy/ast/expr/MethodCallExpression;Lorg/codehaus/groovy/ast/stmt/BlockStatement;
)Lorg/codehaus/groovy/ast/expr/MethodCallExpression;

**Comment by jameskleeh** [comment]
Try GORM 6.1.3

**Comment by virtualcook** [comment]
With
gormVersion=6.1.3.RELEASE

:compileGroovystartup failed:
General error during canonicalization: Cannot cast object 'org.codehaus.groovy.ast.expr.ListExpression@56f77ff0[ConstantExpression[testcatchevalue]]' with class 'org.codehaus.groovy.ast.expr.ListExpression' to class 'org.codehaus.groovy.ast.expr.ConstantExpression'

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.codehaus.groovy.ast.expr.ListExpression@56f77ff0[ConstantExpression[testcatchevalue]]' with class 'org.codehaus.groovy.ast.expr.ListExpression' to class 'org.codehaus.groovy.ast.expr.ConstantExpression'
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnSAM(DefaultTypeTransformation.java:405)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.continueCastOnNumber(DefaultTypeTransformation.java:319)
	at org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation.castToType(DefaultTypeTransformation.java:232)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.castToType(ScriptBytecodeAdapter.java:603)
	at org.grails.plugin.cache.compiler.AbstractCacheTransformation.declareCache(AbstractCacheTransformation.groovy:125)
	at org.grails.plugin.cache.compiler.CacheEvictTransformation.buildDelegatingMethodCall(CacheEvictTransformation.groovy:59)
	at org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.weaveNewMethod(AbstractMethodDecoratingTransformation.groovy:176)
	at org.grails.datastore.gorm.transform.AbstractMethodDecoratingTransformation.visit(AbstractMethodDecoratingTransformation.groovy:63)
	at org.grails.datastore.gorm.transform.AbstractGormASTTransformation.visit(AbstractGormASTTransformation.groovy:59)
	at org.grails.datastore.gorm.transform.OrderedGormTransformation$TransformationInvocation.invoke(OrderedGormTransformation.groovy:112)
	at org.grails.datastore.gorm.transform.OrderedGormTransformation.visit(OrderedGormTransformation.groovy:57)
	at org.codehaus.groovy.transform.ASTTransformationVisitor.visitClass(ASTTransformationVisitor.java:134)
	at org.codehaus.groovy.transform.ASTTransformationVisitor$2.call(ASTTransformationVisitor.java:178)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1065)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:537)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:174)
	at org.gradle.api.internal.tasks.compile.ApiGroovyCompiler.execute(ApiGroovyCompiler.java:56)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:73)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerWorkerAdapter.execute(AbstractDaemonCompiler.java:64)
	at org.gradle.process.internal.daemon.WorkerDaemonServer.execute(WorkerDaemonServer.java:28)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractDaemonCompiler$CompilerDaemonServer.execute(AbstractDaemonCompiler.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:147)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:129)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

1 error


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileGroovy'.
> Compilation failed; see the compiler error output for details.

**Comment by jameskleeh** [comment]
Please provide an example project

**Comment by virtualcook** [comment]
Exactly what information do you needed?

**Comment by jameskleeh** [comment]
A project that reproduces the problem you are experiencing with the least amount of code possible.

I think you are probably not using the annotations correctly because

```'org.codehaus.groovy.ast.expr.ListExpression@56f77ff0[ConstantExpression[testcatchevalue]]' with class 'org.codehaus.groovy.ast.expr.ListExpression' to class 'org.codehaus.groovy.ast.expr.ConstantExpression'``` says you are providing a list to something that expects a single value.

Can you show the annotation that has the `testcatchevalue` name ?

**Comment by virtualcook** [comment]
Project contains two classes
`
package my

import grails.plugin.cache.Cacheable;
import grails.plugin.cache.CacheEvict;
import grails.transaction.Transactional

@Transactional
class TestCacheService {

	String cachedValue = "not set";
	
	@Cacheable('testcatchevalue')
    public String getValue()
	{
		return cachedValue;
    }
	
	public String setValue(String newValue)
	{
		cachedValue = newValue;
		return cachedValue;
    }
	
	@CacheEvict(value=['testcatchevalue'], allEntries=true)
	public void clearValue()
	{
		log.debug("cleared");
	}
}
`
and
`
package testcache

import my.TestCacheService;

class TestController {

	TestCacheService testCacheService;
	
    def index()
	{
		log.debug("index >"+params);
		if(params.value)
			render(testCacheService.setValue(params.value));
		else
			render(testCacheService.getValue());
	}
	
    def clearName()
    {
		testCacheService.clearValue();
		return("cleared");
    }
}
`

**Comment by jameskleeh** [comment]
You aren't using the `@CacheEvict` correctly.

`@CacheEvict(value=['testcatchevalue'], allEntries=true)` > `@CacheEvict('testcatchevalue')`

**Comment by virtualcook** [comment]
CacheEvict from old Grails (before I was using 2.0.4)

Now everything is ok :-)
Thank you

**Comment by jameskleeh** [comment]
@virtualcook Just FYI your issue made me realize the features for CacheEvict were missing in this version. What I noted above will not produce the behavior you expect. If you upgrade to the M2 release you can revert to the old syntax with `allEntries`.
