### ISSUE TITLE
NoClassDefFoundError: FilterRegistrationBean error

### ISSUE THREAD

**Issue by snimavat** [grails-plugins/grails-cache#61]
Grails version - 3.3.9 

```
 compile "org.grails.plugins:cache"
```

Error

```
java.lang.NoClassDefFoundError: org/springframework/boot/context/embedded/FilterRegistrationBean
        at grails.plugin.cache.CacheGrailsPlugin$_doWithSpring_closure1.doCall(CacheGrailsPlugin.groovy:119)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
        at groovy.lang.Closure.call(Closure.java:418)
        at groovy.lang.Closure.call(Closure.java:412)
        at grails.spring.BeanBuilder.invokeBeanDefiningClosure(BeanBuilder.java:759)
        at grails.spring.BeanBuilder.beans(BeanBuilder.java:588)
        at grails.spring.BeanBuilder.invokeMethod(BeanBuilder.java:531)
        at org.grails.plugins.DefaultGrailsPlugin.doWithRuntimeConfiguration(DefaultGrailsPlugin.java:559)
```

**Comment by jameskleeh** [comment]
You likely have something wrong with your project. The version of the plugin that is being brought in is not the one declared in the bom. You can see here there isn't even a line 119 in the plugin class in 4.0.1 (the Grails 3.3.9 bom version). https://github.com/grails-plugins/grails-cache/blob/4d5a4a412510450104f5a132e7cac7777d4bdc07/src/main/groovy/grails/plugin/cache/CacheGrailsPlugin.groovy#L91

https://repo.grails.org/grails/core/org/grails/grails-bom/3.3.9/grails-bom-3.3.9.pom

**Comment by snimavat** [comment]
I see, the issue is dependency on "org.grails.plugins:cache:3.0.2 - which had been put because 
cache 4.0.1 does not have WebKeyGenerator

@jameskleeh any hint what is the alternative to WebKeyGenerator ?
